--Copy the following line to the console to run the experiment
--METaL
--dofile([[H:/machine-learning-project/vr/experiment.lua]])
--mac
--dofile([[/Users/juan/Dropbox/experiment3/vr/experiment.lua]])
